[package]
name = "splits"
version = "0.1.0"
authors = ["murnux <liammurphy@fastmail.com>"]

[dependencies]
serde = "1.0.71"
serde_derive = "1.0.71"
serde_json = "1.0.24"
libsqlite3-sys = "0.9.1"
tera = "0.11"
prettytable-rs = "^0.7"

[dependencies.rusqlite]
version = "0.13.0"
features = ["bundled"]